disabled_rules:
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - file_length
excluded:
  - Carthage
  - Pods
  - R.generated.swift
  - MVPSampleTests/GeneratedMocks.swift
  - vendor/bundle
